# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e9437e6d68f26ab016957a63c9d146b2abd6ee2431022eb59d4ec89f450b500a918d6e1bac01345bbdd00c4dc0dd77edd3d6c3ad429a5c5ecffff7e362e292e

test:
  secret_key_base: 8dfef3df149ce2e743555d809c1e205cd8b71774609fea82bf35f8cc57126f6c835857671976ddf7e0827f6b49b938c479eb80e02e3adbd472f5bc8929b83d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
